[package]
name = "web3-ether-connect-wallet-example"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-console = "0.3.0"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
yew-ethers-provider = { path = "../.." }
